/*DROP SCHEMA public CASCADE;
CREATE SCHEMA public;*/
CREATE TABLE IF NOT EXISTS employees (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     first_name VARCHAR(255) NOT NULL,
                                     last_name VARCHAR(255) NOT NULL,
                                     email VARCHAR(320) NOT NULL UNIQUE,
                                     user_password VARCHAR(12) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS days (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     day_type VARCHAR(50) NOT NULL UNIQUE,
                                     CONSTRAINT pk_days PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS schedule (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    employee BIGINT NOT NULL,
                                    day_type BIGINT NOT NULL,
                                    date_schedule TIMESTAMP NOT NULL,
                                    CONSTRAINT pk_schedule PRIMARY KEY (id),
                                    FOREIGN KEY (employee) REFERENCES employees (id) ON DELETE CASCADE,
                                    FOREIGN KEY (day_type) REFERENCES days (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS tasks_Type (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    task_type VARCHAR(50) NOT NULL UNIQUE,
                                    CONSTRAINT pk_tasksType PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tasks (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     task_name VARCHAR(255) NOT NULL,
                                     description VARCHAR(1024) NOT NULL,
                                     task_type BIGINT NOT NULL,
                                     duration INTEGER CHECK (duration > 0 AND duration <= 480) NOT NULL,
                                     start_Date DATE NOT NULL,
                                     employee BIGINT NOT NULL,
                                     CONSTRAINT pk_task PRIMARY KEY (id),
                                     FOREIGN KEY (employee) REFERENCES employees (id) ON DELETE CASCADE,
                                     FOREIGN KEY (task_type) REFERENCES tasks_type (id) ON DELETE CASCADE
);